[package]
name = "tcpclient"
version = "0.1.0"
authors = ["Samir Satam <ssatam.ctr@kr.af.mil>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "tcpclient"
path = "src/main.rs"

[dependencies]
